[package]
name = "launchpad-tests"
version = "0.1.0"
edition = "2021"

[[test]]
name = "harness"
path = "tests/harness.rs"
harness = true

[dependencies]
fuels = { workspace = true }
tokio = { workspace = true }
rand = "0.8"

[dev-dependencies]