# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: Launchpad
        address:
          - 0x732a37e72cb2664ac09cdde172c722745b9e7e201f34e76eb6471fb561c6bbf2
        abi_file_path: abis/launchpad-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: CampaignLaunchedEvent
            logId: '14024137344589623889'
          - name: CampaignMigratedEvent
            logId: '10134986988804840532'
          - name: BuyEvent
            logId: '16560770387918921138'
          - name: TotalSupplyEvent
            logId: '8807078256608655330'
          - name: MintEvent
            logId: '10159620282815190840'
          - name: CampaignCreatedEvent
            logId: '1830997786495440415'
          - name: PledgedEvent
            logId: '17276933148737557424'
          - name: SellEvent
            logId: '8709694070647771023'
          - name: ClaimEvent
            logId: '2279040052662566249'
          - name: CampaignDeniedEvent
            logId: '12980308201962632363'
      - name: Cinder
        address:
          - 0x4214e6fc579b26d42bf87d77e0f58a027905050503d361ab4cfdcd74f69f4042
        abi_file_path: abis/cinder-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: SetImageEvent
            logId: '13997553477648142054'
          - name: StrLog
            logId: '10098701174489624218'
          - name: InitializeEvent
            logId: '10485970385165293146'
          - name: SetOwnerEvent
            logId: '1320396085097728272'
          - name: TotalSupplyEvent
            logId: '8807078256608655330'
      - name: ReactorPool
        address:
          - 0xa5843e9c21e5039d527b25b45c8f3c28ca33258ae52e6350764024ef24831966
        abi_file_path: abis/reactor-pool-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: CreatePoolEvent
            logId: "12224862438738316526"
          - name: MintEvent
            logId: "12547144180067087194"
          - name: SwapEvent
            logId: "7938487056892321597"
preload_handlers: true
