# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 54700000
    contracts:
      - name: Launchpad
        address:
          - 0xf9877f27adf45934199405c7367f59bb026b0b13c2dfc0f87e6c4428a6b7f325
        abi_file_path: abis/launchpad-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: CampaignLaunchedEvent
            logId: '14024137344589623889'
          - name: CampaignMigratedEvent
            logId: '10134986988804840532'
          - name: BuyEvent
            logId: '16560770387918921138'
          - name: TotalSupplyEvent
            logId: '8807078256608655330'
          - name: MintEvent
            logId: '10159620282815190840'
          - name: CampaignCreatedEvent
            logId: '1830997786495440415'
          - name: PledgedEvent
            logId: '17276933148737557424'
          - name: SellEvent
            logId: '8709694070647771023'
          - name: ClaimEvent
            logId: '2279040052662566249'
          - name: CampaignDeniedEvent
            logId: '12980308201962632363'
          - name: BoostEvent
            logId: '4146107088254613211'
      - name: Cinder
        address:
          - 0xd3bcd74f5b94bf797430b887ac1413c4d9d71b634f2080a2f8ea6193028c9e3a
        abi_file_path: abis/cinder-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: SetImageEvent
            logId: '13997553477648142054'
          - name: StrLog
            logId: '10098701174489624218'
          - name: InitializeEvent
            logId: '10485970385165293146'
          - name: SetOwnerEvent
            logId: '1320396085097728272'
          - name: MintEvent
            logId: '10159620282815190840'
          - name: BurnEvent
            logId: '12646749936579834261'
      - name: ReactorPool
        address:
          - 0xa5843e9c21e5039d527b25b45c8f3c28ca33258ae52e6350764024ef24831966
        abi_file_path: abis/reactor-pool-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: CreatePoolEvent
            logId: "12224862438738316526"
          - name: MintEvent
            logId: "12547144180067087194"
          - name: SwapEvent
            logId: "7938487056892321597"
preload_handlers: true
