[workspace]
resolver = "2"

members = [
    "cinder",
    "launchpad",
]

[workspace.dependencies]
fuels = { version = "0.76", features = ["fuel-core-lib"] }
tokio = { version = "1", features = ["rt", "macros"] }