[project]
authors = ["pdpvs"]
entry = "main.sw"
license = "Apache-2.0"
name = "cinder"

[dependencies]
src20 = "0.8.1"
src3 = "0.8.1"
src7 = "0.8.1"
src5 = "0.8.1"
types = { path = "../libs/types" }
utils = { path = "../libs/utils" }
